/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AppointmentSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'date', 'endTime', 'id', 'images', 'notes', 'patientId', 'specialty', 'startTime', 'status', 'templateId', 'updatedAt', 'userId'] as const
  $columns = AppointmentSchema.$columns
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare images: string | null
  @column()
  declare notes: string | null
  @column()
  declare patientId: number
  @column()
  declare specialty: string
  @column()
  declare startTime: string
  @column()
  declare status: string
  @column()
  declare templateId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'companyId', 'createdAt', 'id', 'newData', 'oldData', 'recordId', 'tableName', 'updatedAt', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare newData: any | null
  @column()
  declare oldData: any | null
  @column()
  declare recordId: number
  @column()
  declare tableName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['address', 'cnpj', 'createdAt', 'crefito', 'email', 'id', 'logoUrl', 'maxPhysios', 'maxSecretaries', 'name', 'phone', 'plan', 'status', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column()
  declare address: string | null
  @column()
  declare cnpj: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare crefito: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoUrl: string | null
  @column()
  declare maxPhysios: number | null
  @column()
  declare maxSecretaries: number | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare plan: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomFieldSchema extends BaseModel {
  static $columns = ['createdAt', 'fieldType', 'group', 'helpText', 'id', 'isRequired', 'label', 'moduleId', 'options', 'sortOrder', 'unit', 'updatedAt'] as const
  $columns = CustomFieldSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fieldType: string
  @column()
  declare group: string | null
  @column()
  declare helpText: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRequired: boolean | null
  @column()
  declare label: string | null
  @column()
  declare moduleId: number | null
  @column()
  declare options: string | null
  @column()
  declare sortOrder: number | null
  @column()
  declare unit: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomModuleSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = CustomModuleSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class EvaluationSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'id', 'overall', 'patientId', 'scores', 'updatedAt'] as const
  $columns = EvaluationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare overall: number
  @column()
  declare patientId: number
  @column()
  declare scores: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FinancialRecordSchema extends BaseModel {
  static $columns = ['amount', 'appointmentId', 'category', 'companyId', 'createdAt', 'date', 'id', 'paidAt', 'patientId', 'paymentMethod', 'recipientUserId', 'referenceMonth', 'status', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = FinancialRecordSchema.$columns
  @column()
  declare amount: string
  @column()
  declare appointmentId: number | null
  @column()
  declare category: string | null
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare patientId: number | null
  @column()
  declare paymentMethod: string
  @column()
  declare recipientUserId: number | null
  @column()
  declare referenceMonth: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FormTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'moduleIds', 'title', 'updatedAt', 'userId'] as const
  $columns = FormTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare moduleIds: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class PatientFormRecordSchema extends BaseModel {
  static $columns = ['answers', 'createdAt', 'id', 'images', 'notes', 'patientId', 'recordDate', 'signatureImage', 'signatureStatus', 'signatureToken', 'signedAt', 'signedByCpf', 'signedByName', 'templateId', 'updatedAt', 'userId'] as const
  $columns = PatientFormRecordSchema.$columns
  @column()
  declare answers: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare images: string | null
  @column()
  declare notes: string | null
  @column()
  declare patientId: number | null
  @column.date()
  declare recordDate: DateTime
  @column()
  declare signatureImage: string | null
  @column()
  declare signatureStatus: string
  @column()
  declare signatureToken: string | null
  @column.dateTime()
  declare signedAt: DateTime | null
  @column()
  declare signedByCpf: string | null
  @column()
  declare signedByName: string | null
  @column()
  declare templateId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class PatientSchema extends BaseModel {
  static $columns = ['birthdate', 'companyId', 'cpf', 'createdAt', 'email', 'emergencyContact', 'gender', 'id', 'maritalStatus', 'name', 'notes', 'phone', 'sessionRate', 'templateId', 'updatedAt', 'userId'] as const
  $columns = PatientSchema.$columns
  @column.date()
  declare birthdate: DateTime
  @column()
  declare companyId: number | null
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare emergencyContact: string | null
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maritalStatus: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string
  @column()
  declare sessionRate: string | null
  @column()
  declare templateId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SatisfactionSurveySchema extends BaseModel {
  static $columns = ['answeredAt', 'companyId', 'createdAt', 'feedback', 'id', 'npsScore', 'patientId', 'recoveryRating', 'status', 'structureRating', 'therapistRating', 'token', 'updatedAt', 'userId'] as const
  $columns = SatisfactionSurveySchema.$columns
  @column.dateTime()
  declare answeredAt: DateTime | null
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedback: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare npsScore: number | null
  @column()
  declare patientId: number
  @column()
  declare recoveryRating: number | null
  @column()
  declare status: string
  @column()
  declare structureRating: number | null
  @column()
  declare therapistRating: number | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class SavedClinicalReportSchema extends BaseModel {
  static $columns = ['companyId', 'createdAt', 'id', 'patientId', 'reportText', 'scaleKey', 'scaleTitle', 'tone', 'updatedAt', 'userId'] as const
  $columns = SavedClinicalReportSchema.$columns
  @column()
  declare companyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare patientId: number
  @column()
  declare reportText: string
  @column()
  declare scaleKey: string
  @column()
  declare scaleTitle: string
  @column()
  declare tone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['active', 'avatarUrl', 'bankInfo', 'baseSalary', 'commissionPercentage', 'companyId', 'compensationType', 'cpfCnpj', 'createdAt', 'crefito', 'email', 'fullName', 'id', 'password', 'paymentDay', 'phone', 'pixKey', 'role', 'sessionRate', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare avatarUrl: string | null
  @column()
  declare bankInfo: string | null
  @column()
  declare baseSalary: string | null
  @column()
  declare commissionPercentage: string | null
  @column()
  declare companyId: number | null
  @column()
  declare compensationType: string | null
  @column()
  declare cpfCnpj: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare crefito: string
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare paymentDay: number | null
  @column()
  declare phone: string | null
  @column()
  declare pixKey: string | null
  @column()
  declare role: string
  @column()
  declare sessionRate: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
